-- CreateTable
CREATE TABLE "Plant" (
    "id" SERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "scientificName" TEXT[],
    "otherName" TEXT[],
    "images" TEXT[],
    "cycle" TEXT NOT NULL,
    "watering" TEXT NOT NULL,
    "depth_water_requirement" TEXT NOT NULL,
    "volume_water_requirement" TEXT NOT NULL,
    "watering_period" TEXT NOT NULL,
    "watering_general_benchmark" TEXT NOT NULL,
    "sunlight" TEXT[],
    "pruning_month" TEXT[],
    "pruningCount" TEXT NOT NULL,
    "flowers" BOOLEAN NOT NULL,
    "flowering_season" TEXT NOT NULL,
    "fruits" BOOLEAN NOT NULL,
    "cones" BOOLEAN NOT NULL,
    "fruiting_season" TEXT[],
    "harvest_season" TEXT[],
    "harvest_method" TEXT[],
    "leaf" BOOLEAN NOT NULL,
    "growth_rate" TEXT NOT NULL,
    "maintenance" TEXT NOT NULL,
    "medicinal" BOOLEAN NOT NULL,
    "edible_leaf" BOOLEAN NOT NULL,
    "poisonous_to_humans" BOOLEAN NOT NULL,
    "poisonous_to_pets" BOOLEAN NOT NULL,
    "drought_tolerant" BOOLEAN NOT NULL,
    "salt_tolerant" BOOLEAN NOT NULL,
    "thorny" BOOLEAN NOT NULL,
    "invasive" BOOLEAN NOT NULL,
    "cuisine" BOOLEAN NOT NULL,
    "indoor" BOOLEAN NOT NULL,
    "care_level" TEXT NOT NULL,
    "rare_level" TEXT NOT NULL,
    "rare" BOOLEAN NOT NULL,
    "description" TEXT NOT NULL,

    CONSTRAINT "Plant_pkey" PRIMARY KEY ("id")
);
